In [1]:
%matplotlib inline

# Tensors

テンソルは特殊なデータ構造で、配列や行列によく似ています。PyTorchでは、テンソルを使ってモデルの入力と出力、モデルのパラメータをエンコードします。
  
テンソルは[NumPy](https://numpy.org/)のndarraysに似ていますが、テンソルはGPUや他のハードウェアアクセラレータ上で動作することができます。実際、テンソルとNumPyの配列は、しばしば同じ基礎メモリを共有することができ、データをコピーする必要がありません（bridge-to-np-labelを参照）。テンソルはまた、自動微分にも最適化されています（これについては後ほどAutogradユニットで詳しく見ていきます）。ndarraysに慣れている人は、Tensor APIをすぐに使いこなせるだろう。そうでない場合は、ついてきてください
  
まずは、環境を整えることから始めよう。


In [2]:
import torch
import numpy as np

# テンソルの初期化

テンソルは様々な方法で初期化することができます。以下の例を見てみましょう。

## データからの直接入力

テンソルはデータから直接作成することができます。データの種類は自動的に推測されます。
テンソルは特殊なデータ構造で、配列や行列によく似ています。PyTorchでは、テンソルを使ってモデルの入力と出力、モデルのパラメータをエンコードします。


In [3]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

## NumPyの配列から

NumPyの配列からテンソルを作成することができます（その逆も可能です - `bridge-to-np-label`を参照）。


In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

## 別のテンソルから

新しいテンソルは、明示的にオーバーライドされていない限り、引数のテンソルのプロパティ（形状、データ型）を保持します。


In [5]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6541, 0.0348],
        [0.5640, 0.7520]]) 



## ランダムまたは一定の値を持つ

`shape` はテンソルの次元を表すタプルである。以下の関数では、出力されるテンソルの次元を決定します。


In [7]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.7516, 0.3579, 0.2962],
        [0.5499, 0.9865, 0.0020]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


# テンソルの属性

テンソルの属性は、その形状、データタイプ、保存されているデバイスなどを表す。


In [8]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# テンソルの演算

算術、線形代数、行列操作（転置、インデックス、スライス）など、100以上のテンソル演算が可能です。
演算、線形代数、行列操作（転置、索引、スライス）、サンプリングなど、100以上のテンソル演算が
総合的に説明されています[こちら](https://pytorch.org/docs/stable/torch.html)。

これらの演算は、GPU上で実行することができます（通常、CPU上よりも高速に実行できます）。
CPUよりも高速に）実行することができます。)

デフォルトでは、テンソルは CPU で作成されます。
`.to` メソッドを使って、明示的にテンソルをGPUに移動させる必要があります（GPUの利用可能性をチェックした後）。大きなテンソルをデバイス間でコピーすると、時間とメモリの面でコストがかかることを覚えておいてください。


In [9]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

リストの中からいくつかの操作を試してみましょう。
NumPy APIに慣れている人は、Tensor APIも簡単に使えると思う。

## 標準的なnumpyのようなインデックスとスライス

In [10]:
tensor = torch.ones(4, 4)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


## テンソルの結合

与えられた次元に沿って一連のテンソルを連結するには、`torch.cat` を使います。
[torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html)も参照してください。
これは `torch.cat` とは微妙に異なるテンソル結合関数です。

In [11]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


## 算術演算

In [12]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

## 1要素のテンソル

例えば、テンソルのすべての値を1つの値に集約して、1要素のテンソルを作成した場合、`item()` を使って Python の数値に変換することができます。



In [13]:
agg = tensor.sum()
agg_item = agg.item()  
print(agg_item, type(agg_item))

12.0 <class 'float'>


## インプレイス演算
結果をオペランドに格納する演算をインプレイス演算と呼びます。これは `_` という接尾辞で示されます。
例えば、 `x.copy_(y)`, `x.t_()` は `x` を変更します。

> **Note:** インプレース操作はメモリを節約できます、履歴がすぐに失われるため、微分を計算する際には問題となります。そのため、その使用は推奨されません。



In [14]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## NumPyとのブリッジ

CPU上のテンソルとNumPyアレイは、その下のメモリロケーションを共有することができます。
しており、一方を変更すると他方も変更されます。

### テンソルからNumPy配列へ

In [15]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.


In [16]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### NumPyの配列からTensorへ

In [17]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the NumPy array reflects in the tensor.


In [18]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


# ♪あなたの知識をチェック

1. テンソルについて正しいのはどれですか？

* テンソルは、ベクトルを表す文字列型です。
  > 不正解

* テンソルは、PythonでGPS座標を表現する数学的な値です。
  > 不正解

* テンソルは、配列や行列に似た特殊なデータ構造です。
  > 正解